name: 'Get cached dependencies'
description: 'Caches dependencies to speed up workflow runs'
inputs:
  caching:
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
outputs:
  cache-hit:
    description: 'Whether the cache was hit or not'
    value: ${{ steps.Install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: Install
      if: steps.cache.outputs.cache-hit != 'true' || ${{ inputs.caching != 'true' }}
      run: |
        npm ci
        echo "::set-output name=cache::${{ inputs.caching }}"
      shell: bash